const actionTypes = {
  GET_RECIPE: 'GET_RECIPE',
  GET_RECIPE_BY_NAME: 'GET_RECIPE_BY_NAME',
  GET_RECIPE_BY_NAME_ERROR: 'GET_RECIPE_BY_NAME_ERROR',
  RESTORE_SEARCH_REDUCER: 'RESTORE_SEARCH_REDUCER',
  GET_RECIPE_CATEGORIES: 'GET_RECIPE_CATEGORIES',
  GET_CATEGORY_RECIPES: 'GET_CATEGORY_RECIPES',
  RESTORE_CATEGORY_RECIPES_REDUCER: 'RESTORE_CATEGORY_RECIPES_REDUCER',
  GET_CATEGORY_RECIPE_BY_NAME: 'GET_CATEGORY_RECIPE_BY_NAME',
  RESTORE_CATEGORY_RECIPE_BY_NAME_REDUCER: 'RESTORE_CATEGORY_RECIPE_BY_NAME_REDUCER',
  GET_PRODUCT_TYPE: 'GET_PRODUCT_TYPE',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  DELETE_ALL_PRODUCTS: 'DELETE_ALL_PRODUCTS',
  CROSS_OVER_PRODUCT: 'CROSS_OVER_PRODUCT',
  USER_IS_LOGGED_IN: 'USER_IS_LOGGED_IN',
};

export default actionTypes;
