import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  header: {
    position: 'absolute',
    top: 0,
    zIndex: 1,
    width: '100%',
    height: 50,
    backgroundColor: 'rgb(230, 84, 84)',
    paddingHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 29,
    color: 'black',
    textShadowColor: 'white',
    textShadowOffset: { width: 2, height: 2 },
    marginHorizontal: 50,
    borderBottomWidth: 0.7,
    borderBottomColor: 'black',
    marginBottom: 25,
    paddingTop: 10,
    textAlign: 'center',
    paddingBottom: 1,
  },
  menuCard: {
    borderRadius: 5,
    backgroundColor: 'rgb(242, 242, 242)',
    elevation: 5,
    marginHorizontal: 10,
    marginBottom: 15,
  },
  weekContainer: {
    flexDirection: 'row',
    height: 50,
    alignItems: 'center',
    marginTop: 70,
  },
  dayWrapper: {
    backgroundColor: 'rgb(58, 58, 58)',
    borderColor: 'white',
    borderWidth: StyleSheet.hairlineWidth,
    height: 50,
    borderRadius: 3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  recipeImage: {
    height: 100,
    width: 155,
    borderRadius: 5,
    marginRight: 15,
  },
  recipeNameWrapper: {
    flexGrow: 1,
    paddingRight: 15,
    justifyContent: 'center',
    flexDirection: 'row',
  },
  recipeNameContainer: {
    fontSize: 20,
    flex: 1,
    flexWrap: 'wrap',
    textAlign: 'center',
    marginTop: 5,
  },
  addMenuButtonContainer: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: 'rgb(150, 89, 42)',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
  },
  addMenuButton: {
    fontSize: 70,
    fontFamily: 'serif',
    color: 'white',
    textShadowColor: 'black',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  addMenuText: {
    fontSize: 20,
    width: 240,
    textAlign: 'center',
    position: 'relative',
    top: 55,
    lineHeight: 30,
  },
  arrow: {
    width: 75,
    height: 85,
    position: 'relative',
    right: 130,
  },
});

export default styles;
